PAGE_SIZE = 6

MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150

MAX_LENGTH_RECIPE = 254

MIN_COOKING_TIME = 1
MIN_INGREDIENT = 1
MAX_INGREDIENT = 100

MAX_LENGTH_LINK = 10
LENGTH_SHORT_LINK = 5
